### ISSUE TITLE
Current status of Micro frontends?

### ISSUE THREAD

**Issue by tomsoderlund** [neuland/micro-frontends#1]
Hi @neuland! Is this project active?

You're mentioned here:

https://medium.com/@tomsoderlund/micro-frontends-a-microservice-approach-to-front-end-web-development-f325ebdadc16

**Comment by naltatis** [comment]
Great blogpost! Yes the project is still active. There will be new content in the next weeks. Thanks for mentioning.

**Comment by naltatis** [comment]
Now I've reached the content I was planning for v1. More is coming, but I'm closing the issue now ...
