### ISSUE TITLE
Suggestion: have a look at the Java Portlet specifications

### ISSUE THREAD

**Issue by yuchi** [neuland/micro-frontends#20]
The Java Portlet Specification [(Wikipedia)](https://en.wikipedia.org/wiki/Java_Portlet_Specification) more or less tries to cover exactly what this project is all about, but the concept of a Component is called Portlet, and the scope of a “unit of functional collaboration” is a little bit bigger (a Portlet is a big page fragment, while a Component tends to be smaller).

There are many implementation of those specifications, but I suggest you to have a look at [Liferay’s](https://github.com/liferay/liferay-portal).

**Comment by naltatis** [comment]
Thanks for the suggestion. Looks interesting. The focus of this spec seems to be focused around building sharepoint style enterprise portals, hence the name. Many concepts are directly related to the approach describe here (namespacing, resource loading, ...) but some are also very portal specific (storing portlet preferences, portlet titles, shared runtime). I'll read deeper into this spec, when I find some time.

I've added a reference https://github.com/neuland/micro-frontends/commit/859afe70152e7edeefacec351d162cb568baae87 to the Java Portlet Specification in the "Related Techniques" area at the end of the page.
