### ISSUE TITLE
Apply for translation

### ISSUE THREAD

**Issue by fyz1994** [neuland/micro-frontends#23]
hi,I am a front-end developer from China, can I have the honor to translate this article into Chinese?

**Comment by GrosSacASac** [comment]
Hello, according to the latest activity on this repo, the owners are not looking too much at open issues ...
Follow the license and it is good to translate
https://github.com/neuland/micro-frontends/blob/master/LICENSE

**Comment by BeneStem** [comment]
wow! That sounds really cool :) 
That is a great way to reach more people and let the community grow even more!

What are the maintainers thinking about that?

**Comment by BeneStem** [comment]
I can contact the owner in person and he will notify you :)

But yes following the LICENSE is usually a well approach.

**Comment by naltatis** [comment]
Hi @fyz1994, yes you can definitely do a translation. I would be honored. @koiketakayuki did the Japanese translation in his own repository and we added links to each other. For the start I would recommend doing the same for Chinese.

At some point it might make sense to fold all translations back into this repository. But for now this solution is fine.

Fyi, I’m planning to add new content in the next weeks and will break up the article into multiple topic pages.

**Comment by arhont375** [comment]
@naltatis Hi, I would like to translate this article into Russian.

**Comment by naltatis** [comment]
@arhont375 Nice!

**Comment by naltatis** [comment]
Russian and Chinese translations have been added. More translations are always welcome.
