### ISSUE TITLE
Team Blue Missing!

### ISSUE THREAD

**Issue by SpellChucker** [neuland/micro-frontends#28]
With the latest commit, team blue is missing! Therefore the `DockerFile` can't find it.

201829e6e81fe6268db80d82efd8b3334201d1a1

**Comment by naltatis** [comment]
Hi @SpellChucker,
thanks for the issue. I indeed cleanup up a little too much. Wanted to remove the `build` folders but accidentally eliminated the complete team :)
Now it should work again.

All the best, Michael
