### ISSUE TITLE
Thanks about micro-frontends concept.

### ISSUE THREAD

**Issue by afsec** [neuland/micro-frontends#32]
@naltatis 

Thanks about your micro-frontends initiative. I was inspired and made my own framework.

https://github.com/afsec/cellular-js

Cheers!

**Comment by naltatis** [comment]
@afsec Thanks for your contribution. I've added it to my list of tools to examine further :)
I'm planning to expand the site in the future and add a "tools" section where libraries like yours can be aggregated and maybe compared.

You should propose your project to the awesome lists of @ChristianUlbrich and @rajasegar.
