### ISSUE TITLE
Added Portuguese Translation

### ISSUE THREAD

**Issue by Tautorn** [neuland/micro-frontends#37]
Hi there. 

I did translate micro-frontends to Portuguese, but I don't buy a domain like in JP and ES version.

Can I keep in my own github page domain?

https://tautorn.github.io/micro-frontends/

**Comment by naltatis** [comment]
Nice one 🤩 Yes, having a custom domain is definitely optional.
Thanks for your work. I've added your site to the header and meta data and put your name into the contributors list at the bottom.

💚 Michael
