### ISSUE TITLE
Added Korean Translation

### ISSUE THREAD

**Issue by soobing** [neuland/micro-frontends#42]
I translated micro-frontend into Korean.
Can I use domain with github pages?

These are should be added.
```
<link rel="alternate" hreflang="ko" href="https://soobing.github.io/micro-frontends/" />
```

```
<a href="https://soobing.github.io/micro-frontends/">KR</a>
```

```
- [Soobin Bak](https://github.com/soobing) who translated the site to [Korean](https://soobing.github.io/micro-frontends/).
```

Thanks for nice article with examples 👍🏻

**Comment by soobing** [comment]
@naltatis Hi ~~~ 😃

**Comment by naltatis** [comment]
Hi @soobing, thanks for the translation. I'll add the references later today.
And yes, using a GitHub pages domain is perfectly fine for me.

**Comment by naltatis** [comment]
I've added the references. Thanks for your work @soobing! 🍒
