### ISSUE TITLE
Misleading diagram wrt frameworks

### ISSUE THREAD

**Issue by ewolff** [neuland/micro-frontends#49]
https://github.com/neuland/micro-frontends/blob/master/ressources/screen/three-teams.png seems to indicate that the three teams should use three different frameworks (Vue, React, Angular). At least the logos for these frameworks are present in the screen. However, that is not what the example code seems to use. Also this approach would use a lot of resources and slow down loading the application and page. It would therefore be great to remove the logos from the figure. Also it would be great if the page explicitly talk about the problems such a multitude of frameworks might cause.

**Comment by naltatis** [comment]
Hi @ewolff. Yes, the diagram shows these different frameworks side by side to illustrate the level of isolation and autonomy we should aim for. In contrast to integration through the component system of one specific framework. But I agree that the diagram and surrounding text should be updated to make this clear.

**Comment by naltatis** [comment]
I've removed the framework logos from the diagram and added a "Avoid Framework Anarchy" section to the content.
