### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by lawrence31983** [neuland/micro-frontends#6]
Hey, 

Is there a tutorial on getting this to build. I have webpack installed, docker installed but getting this error. 

team_red_1    | ERROR in Entry module not found: Error: Can't resolve './src/client.js' in '/code'
team_red_1    | npm ERR! code ELIFECYCLE
team_red_1    | npm ERR! errno 2
team_red_1    | npm ERR! team-red@1.0.0 build: `webpack -p`
team_red_1    | npm ERR! Exit status 2
team_green_1  |

Thanks

**Comment by naltatis** [comment]
Can you give some more detail?
Which project did you try to build? OS & Docker Version?

**Comment by lawrence31983** [comment]
I was following the directions on https://micro-frontends.org/  The section where it says you can play this sample coade on your local machine. Only Docker Compose needs to be installed. Thin it gives you git clone instructions and then you run the command docker –compose up --build

**Comment by naltatis** [comment]
Ok, this looks like an issue with mounting the `src` directories to the docker container. I've added this to make it easy to change code without having to restart the containers. I've tested it on macOS. Not quite sure if there is something special you have to do on window.

Could you try to delete the three `volumes:` entries from the `docker-compose.yaml` file?

**Comment by lawrence31983** [comment]
Still had issues. I ended up spinning up on my linux box and it built etc fine.

**Comment by naltatis** [comment]
Ok, if someone knows how to get this to work on windows, please let me know.
But for now, I'll close this issue.
