### ISSUE TITLE
Universal Composition: Render Call Question

### ISSUE THREAD

**Issue by ThanosAlmighty** [neuland/micro-frontends#60]
Noticed a call to a render(sku) function on line 23 from the sibling level import of render.js

![image](https://user-images.githubusercontent.com/32068435/136569439-14e4bc65-3b6e-44fe-904f-92ff8d608d6d.png)

When I look at the function in the file, however, the static function name is actually renderRecos().

![image](https://user-images.githubusercontent.com/32068435/136569866-7dede915-5974-4f3f-9e48-a155b36f08f3.png)

 Is this a typo, or am I missing something?

**Comment by naltatis** [comment]
`renderRecos` is the default export of the `render.js` file.
In `custom-element.js` imports the module and saves the default export under the name `render` locally.
I could also have omitted the `renderRecos` name and only provide an anonymous function but I named it for better readability.

**Comment by ThanosAlmighty** [comment]
> `renderRecos` is the default export of the `render.js` file. In `custom-element.js` imports the module and saves the default export under the name `render` locally. I could also have omitted the `renderRecos` name and only provide an anonymous function but I named it for better readability.

Okay! This is just my lack of familiarity with raw JS. Thanks for clarifying
