### ISSUE TITLE
Integrate micro frontend from different repo?

### ISSUE THREAD

**Issue by rangrasjay** [neuland/micro-frontends#61]
Here, we are planning to move all of our common components to one different repo and then integrate it with with our all other portals which are on again different different repos. My question is, how to integrate it? I tried to integrate it in package.json and fetch repo along with branch as module. But that didn't worked on azure. Now, I am going to try git submodules. Please tell me is it a correct way or do I need to try something else?

**Comment by naltatis** [comment]
For us, each team has it's own repository and CI/CD pipeline. We try to share as little as possible to minimize inter-team dependencies. For components we need to share (e.g. a central design system) a good way ist to have them in a separate repository and publish it as an NPM package. This way each team is free to install and upgrade the shared dependencies at their own pace.
