### ISSUE TITLE
Added Polish translation

### ISSUE THREAD

**Issue by dominikcz** [neuland/micro-frontends#83]
Hi, I translated micro-frontend into Polish.

These are should be added.

`<link rel="alternate" hreflang="pl" href="https://dominikcz.github.io/micro-frontends/" />`

`<a href="https://dominikcz.github.io/micro-frontends/">PL</a>`

`- [Dominik Czechowski](https://github.com/dominikcz) who translated the site to [Polish](https://dominikcz.github.io/micro-frontends/).`

Thank you for your great work ❤

**Comment by naltatis** [comment]
Thanks for your translation. I've updated the site 💚
