### ISSUE TITLE
you may want to remove manufactum as a reference

### ISSUE THREAD

**Issue by eavichay** [neuland/micro-frontends#9]
Their website is built with react and babelized.

**Comment by naltatis** [comment]
This is the site we are currently working on and have implemented the described techniques.
Yes, both teams chose to go with react for implementing their pages and fragments.

Micro Frontends is not about using or not using a specific technology. The important thing is to enable all end-to-end teams to develop end evolve their software independently from other teams and avoiding to build a frontend monolith.
